In [1]:
import pandas as pd
import numpy as np

In [3]:
import os
os.getcwd()

'c:\\Users\\Shiva\\Desktop\\Python + powerbi project'

In [5]:
df = pd.read_excel("Python_PowerBI_Dirty_Sales_Dataset.xlsx")

In [6]:
df.head(5)

,Order_ID,Order_Date,Customer_Name,Region,Category,Product,Quantity,Unit_Price,Sales,Profit,Discount
0,ORD1002,2025-10-03,Eva,South,Office Supplies,Paper,1,500,500,7.27,120.0
1,ORD1003,2025-09-07,David,South,Electronics,Mouse,5,100,500,113.14,120.0
2,ORD1004,2025-08-11,Eva,East,Office Supplies,Paper,-2,250,-500,-33.60,15.0
3,ORD1005,2025-07-12,NaN,North,Office Supplies,Paper,-2,50,-100,-8.78,NaN
4,ORD1006,2025-06-26,Bob,NaN,Office Supplies,Pen,1,1000,1000,-93.73,10.0

In [7]:
df.shape

(500, 11)

In [8]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Region', 'Category',
       'Product', 'Quantity', 'Unit_Price', 'Sales', 'Profit', 'Discount'],
      dtype='object')

In [9]:
df.dtypes

Order_ID          object
Order_Date        object
Customer_Name     object
Region            object
Category          object
Product           object
Quantity          object
Unit_Price        object
Sales             object
Profit           float64
Discount         float64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       500 non-null    object
 1   Order_Date     500 non-null    object
 2   Customer_Name  351 non-null    object
 3   Region         379 non-null    object
 4   Category       374 non-null    object
 5   Product        441 non-null    object
 6   Quantity       441 non-null    object
 7   Unit_Price     441 non-null    object
 8   Sales          359 non-null    object
 9   Profit         270 non-null    float64
 10  Discount       411 non-null    float64
dtypes: float64(2), object(9)
memory usage: 43.1+ KB

In [12]:
import pandas as pd
import numpy as np

df = pd.read_excel("Python_PowerBI_Dirty_Sales_Dataset.xlsx")

df.head()

df.shape

df.columns

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       500 non-null    object
 1   Order_Date     500 non-null    object
 2   Customer_Name  351 non-null    object
 3   Region         379 non-null    object
 4   Category       374 non-null    object
 5   Product        441 non-null    object
 6   Quantity       441 non-null    object
 7   Unit_Price     441 non-null    object
 8   Sales          359 non-null    object
 9   Profit         270 non-null    float64
 10  Discount       411 non-null    float64
dtypes: float64(2), object(9)
memory usage: 43.1+ KB

In [14]:
##  Checking the missing values

df.isnull().sum()

Order_ID           0
Order_Date         0
Customer_Name    149
Region           121
Category         126
Product           59
Quantity          59
Unit_Price        59
Sales            141
Profit           230
Discount          89
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['Order_ID'].duplicated().sum()

np.int64(4)

In [18]:
df.describe(include="all")

,Order_ID,Order_Date,Customer_Name,Region,Category,Product,Quantity,Unit_Price,Sales,Profit,Discount
count,500,500,351,379,374,441,441.0,441,359.0,270.000000,411.000000
unique,496,267,5,4,3,11,7.0,6,32.0,NaN,NaN
top,ORD1046,32-13-2025,Eva,East,Office Supplies,Unknown,5.0,abc,1000.0,NaN,NaN
freq,2,15,84,104,133,67,76.0,85,39.0,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.915148,34.927007
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225.982097,48.543363
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-451.090000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.565000,5.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.840000,10.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.692500,15.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1286.720000,120.000000

In [19]:
df.isnull()

,Order_ID,Order_Date,Customer_Name,Region,Category,Product,Quantity,Unit_Price,Sales,Profit,Discount
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,True
4,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,True,True,False,False,False,False,False,True,False
496,False,False,False,False,False,False,False,False,False,True,False
497,False,False,False,False,True,False,False,False,False,False,False
498,False,False,True,False,False,False,False,False,False,False,False
499,False,False,False,False,True,False,False,False,False,False,False

In [20]:
df["Region"].unique()

array(['South', 'East', 'North', nan, 'West'], dtype=object)

In [21]:
df["Category"].unique()

array(['Office Supplies', 'Electronics', nan, 'Furniture'], dtype=object)

In [23]:
df.isnull().sum()

df.duplicated().sum()

df["Order_ID"].duplicated().sum()

df.describe(include="all")

df["Region"].unique()

df["Category"].unique()

array(['Office Supplies', 'Electronics', nan, 'Furniture'], dtype=object)

In [52]:
#######  Handing missing values

df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
Region           0
Category         0
Product          0
Quantity         0
Unit_Price       0
Sales            0
Profit           0
Discount         0
dtype: int64

In [27]:
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")

In [29]:
df["Region"] = df['Region'].fillna("unknown")

In [31]:
df["Region"] = df["Region"].fillna(df["Region"].mode()[0])

In [33]:
df["Category"] = df["Category"].fillna(df["Category"].mode()[0])

In [35]:
df["Product"] = df["Product"].fillna("Unknown")

In [42]:
df["Quantity"] = df["Quantity"].fillna(0)

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [39]:
df["Quantity"]=pd.to_numeric(df["Quantity"],errors="coerce")

In [40]:
df["Unit_Price"]=pd.to_numeric(df["Unit_Price"],errors="coerce")

In [45]:
df["Unit_Price"] = df["Unit_Price"].fillna(df["Unit_Price"].median())

In [47]:
df["Sales"] = df["Quantity"] * df["Unit_Price"]

In [49]:
df["Profit"] = df["Profit"].fillna(df["Sales"] * 0.20)

In [51]:
df["Discount"] = df["Discount"].fillna(0)

In [55]:
df["Order_ID"].duplicated().sum()

np.int64(0)

In [54]:
df = df.drop_duplicates(subset="Order_ID", keep="first")

In [56]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\3550543220.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

In [59]:
df["Order_Date"].isnull().sum()

np.int64(0)

In [58]:
df["Order_Date"] = df["Order_Date"].fillna(df["Order_Date"].mode()[0])

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\1763500129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Date"] = df["Order_Date"].fillna(df["Order_Date"].mode()[0])

In [60]:
df.dtypes

Order_ID                 object
Order_Date       datetime64[ns]
Customer_Name            object
Region                   object
Category                 object
Product                  object
Quantity                float64
Unit_Price              float64
Sales                   float64
Profit                  float64
Discount                float64
dtype: object

In [61]:
df["Year"] = df["Order_Date"].dt.year

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\3066843155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"] = df["Order_Date"].dt.year

In [62]:
df["Month"] = df["Order_Date"].dt.month

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\4224749752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month"] = df["Order_Date"].dt.month

In [63]:
df["Month_Name"] = df["Order_Date"].dt.month_name()

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\2704293936.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month_Name"] = df["Order_Date"].dt.month_name()

In [64]:
df["Quarter"] = df["Order_Date"].dt.quarter

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\3526010426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quarter"] = df["Order_Date"].dt.quarter

In [65]:
df["Profit_Margin"] = (df["Profit"] / df["Sales"]) * 100

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\3115630862.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Profit_Margin"] = (df["Profit"] / df["Sales"]) * 100

In [66]:
df.head(5)

,Order_ID,Order_Date,Customer_Name,Region,Category,Product,Quantity,Unit_Price,Sales,Profit,Discount,Year,Month,Month_Name,Quarter,Profit_Margin
0,ORD1002,2025-10-03,Eva,South,Office Supplies,Paper,1.0,500.0,500.0,7.27,120.0,2025,10,October,4,1.454
1,ORD1003,2025-09-07,David,South,Electronics,Mouse,5.0,100.0,500.0,113.14,120.0,2025,9,September,3,22.628
2,ORD1004,2025-08-11,Eva,East,Office Supplies,Paper,-2.0,250.0,-500.0,-33.60,15.0,2025,8,August,3,6.720
3,ORD1005,2025-07-12,Unknown,North,Office Supplies,Paper,-2.0,50.0,-100.0,-8.78,0.0,2025,7,July,3,8.780
4,ORD1006,2025-06-26,Bob,unknown,Office Supplies,Pen,1.0,1000.0,1000.0,-93.73,10.0,2025,6,June,2,-9.373

In [67]:
df.to_excel("Cleaned_Sales_Data.xlsx", index=False)

In [68]:
##########   EDA (Exploratory Data Analysis) phase.

total_sales = df["Sales"].sum()
print("Total Sales:", total_sales)

Total Sales: 303850.0

In [ ]:
### Total sales ## 
total_sales = df["Sales"].sum()
print("Total Sales:", total_sales)

Total Sales: 303850.0

In [70]:
####   Total profit  ###

total_profit = df["Profit"].sum()
print("Total Profit:", total_profit)

Total Profit: 36211.479999999996

In [71]:
###  Total Orders  ###

total_orders = df["Order_ID"].nunique()
print("Total Orders:", total_orders)

Total Orders: 496

In [74]:
### Total coustomer  ###

total_customers = df["Customer_Name"].nunique()
print("Total Customers:", total_customers)

Total Customers: 6

In [76]:
###  Pratice

total_customers = df["Customer_Name"].unique()
print("Total_Customer",total_customers)

Total_Customer ['Eva' 'David' 'Unknown' 'Bob' 'Charlie' 'Alice']

In [ ]:
### Top 10 Product by sales  ###

top_products = df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(10)

print(top_products)

Product
Desk        51800.0
Unknown     51650.0
Paper       29500.0
Pen         28500.0
Keyboard    27850.0
Table       26850.0
Binder      23850.0
Chair       23250.0
Mouse       15150.0
Laptop      14700.0
Name: Sales, dtype: float64

In [78]:
###  Region wise sales ###

region_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

print(region_sales)

Region
unknown    83150.0
North      68200.0
East       63200.0
West       47100.0
South      42200.0
Name: Sales, dtype: float64

In [79]:
### Category wise sales ###

category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

print(category_sales)

Category
Office Supplies    133500.0
Furniture          101900.0
Electronics         68450.0
Name: Sales, dtype: float64

In [80]:
### Month sales Trend ##
monthly_sales = df.groupby("Month_Name")["Sales"].sum()

print(monthly_sales)

Month_Name
April        20450.0
August       23100.0
December     17550.0
February     42100.0
January      28350.0
July         10250.0
June         23550.0
March        44350.0
May          22700.0
November     17700.0
October      13750.0
September    40000.0
Name: Sales, dtype: float64

In [87]:

monthly_profit = df.groupby("Month_Name")["Profit"].sum()
print(monthly_profit)

Month_Name
April        2731.41
August       3567.86
December     2126.15
February     1762.11
January      4145.61
July          462.19
June         2383.79
March        6638.34
May          3801.95
November     1563.07
October      1919.30
September    5109.70
Name: Profit, dtype: float64

In [88]:
top_customers = df.groupby("Customer_Name")["Sales"].sum().sort_values(ascending=False).head(10)

print(top_customers)

Customer_Name
Unknown    107550.0
Eva         49400.0
David       44050.0
Charlie     41800.0
Alice       32400.0
Bob         28650.0
Name: Sales, dtype: float64

In [89]:
# Find the most common region
print(df["Region"].mode())

# Replace unknown values
df["Region"] = df["Region"].replace("unknown", df["Region"].mode()[0])
df["Region"] = df["Region"].replace("Unknown", df["Region"].mode()[0])

0    unknown
Name: Region, dtype: object

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\3556208618.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Region"] = df["Region"].replace("unknown", df["Region"].mode()[0])
C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\3556208618.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Region"] = df["Region"].replace("Unknown", df["Region"].mode()[0])

In [90]:
df.to_excel("Cleaned_Sales_Data.xlsx", index=False)

In [91]:
# Replace 'unknown' with the most frequent region
df["Region"] = df["Region"].replace(["unknown", "Unknown"], df["Region"].mode()[0])

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\950073381.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Region"] = df["Region"].replace(["unknown", "Unknown"], df["Region"].mode()[0])

In [92]:
df.to_excel("Cleaned_Sales_Data.xlsx", index=False)

In [93]:
df.to_excel("Cleaned_Sales_Data.xlsx", index=False)

In [94]:
print(df["Order_Date"].dtype)

datetime64[ns]

In [95]:
df["Order_Date"] = df["Order_Date"].dt.strftime("%Y-%m-%d")

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\2362927086.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Date"] = df["Order_Date"].dt.strftime("%Y-%m-%d")

In [96]:
df.to_excel("Cleaned_Sales_Data.xlsx", index=False)

In [98]:
print(df["Order_Date"].dtype)

print(df["Order_Date"].head(10))

object
0    2025-10-03
1    2025-09-07
2    2025-08-11
3    2025-07-12
4    2025-06-26
5    2025-05-06
6    2025-04-15
7    2025-08-16
8    2025-08-26
9    2025-10-19
Name: Order_Date, dtype: object

In [99]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

print(df["Order_Date"].head())
print(df["Order_Date"].dtype)

df.to_excel("Cleaned_Sales_Data.xlsx", index=False)

C:\Users\Shiva\AppData\Local\Temp\ipykernel_21348\3989255313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

0   2025-10-03
1   2025-09-07
2   2025-08-11
3   2025-07-12
4   2025-06-26
Name: Order_Date, dtype: datetime64[ns]
datetime64[ns]

In [100]:
df["Region"] = df["Region"].replace(["unknown", "Unknown"], df["Region"].mode()[0])

df.to_excel("Cleaned_Sales_Data.xlsx", index=False)

In [101]:
df["Region"] = df["Region"].replace("unknown", "North")

In [102]:
df.to_excel("Cleaned_Sales_Data.xlsx", index=False)